# This workflow run the performance test

name: Perf Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
# Todo: remove this,
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-perf-test
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
      - name: Set up JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          gradle-home-cache-cleanup: true
      - name: Run performance benchmarks
        run: ./gradlew runBenchmarks
      - name: Convert results to markdown
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --to=gfm
            --output=benchmark_results.md
            benchmark_results.csv
      - name: Upload results
        run: cat benchmark_results.md >> $GITHUB_STEP_SUMMARY