# This workflow run the performance test

name: Perf Test

on:
  workflow_dispatch:
# Todo: remove this and add one tht runs on merge to main, killing any previous.
#todo: same for func test.
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
      - name: Set up JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install pandoc # used for latex to markdown conversion
        run: | # todo: drop this.
          sudo apt-get update
          sudo apt-get pandoc
      - name: Setup Gradle
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
          gradle-home-cache-cleanup: true
      - name: Run
        run: |
          ./gradlew runBenchmarks
          pandoc benchmark_results.csv -t gfm >> $GITHUB_STEP_SUMMARY
          # todo: split into two steps and use docker